// <auto-generated> by Tools/build_connectome.py. Do not edit by hand. </auto-generated>
// Drosophila circadian -> sleep-homeostat circuit, FlyWire whole-brain connectome v783.
// Data: FlyWire Consortium (Dorkenwald et al. 2024; Schlegel et al. 2024), CC-BY 4.0,
//       connectivity/sign table from Shiu et al. 2024 (github.com/philshiu/Drosophila_brain_model).
// 36 cell-type nodes (260 neurons), 192 edges (28782 synapses).
namespace FlyXenotype.Brain
{
    public static class FlyConnectomeSleep
    {
        public static readonly string[] Types = {
            "s-LNv_a", // 2 neurons, glutamate
            "s-LNv_b", // 8 neurons, acetylcholine
            "LNd_a", // 2 neurons, glutamate
            "LNd_b", // 4 neurons, acetylcholine
            "LNd_c", // 6 neurons, acetylcholine
            "DN1pA", // 8 neurons, glutamate
            "DN1pB", // 4 neurons, glutamate
            "DN1a", // 4 neurons, glutamate
            "TuBu01a", // 4 neurons, acetylcholine
            "TuBu01b", // 7 neurons, acetylcholine
            "TuBu02", // 11 neurons, acetylcholine
            "TuBu03", // 26 neurons, acetylcholine
            "TuBu04", // 9 neurons, acetylcholine
            "TuBu05", // 10 neurons, acetylcholine
            "TuBu06a", // 2 neurons, acetylcholine
            "TuBu06b", // 5 neurons, acetylcholine
            "TuBu07", // 17 neurons, acetylcholine
            "TuBu08", // 22 neurons, acetylcholine
            "TuBu09,TuBu10", // 37 neurons, acetylcholine
            "ER5", // 21 neurons, gaba
            "ExR1", // 4 neurons, acetylcholine
            "ExR3", // 2 neurons, dopamine
            "FB6A", // 4 neurons, glutamate
            "FB6C", // 9 neurons, glutamate
            "FB6E", // 2 neurons, glutamate
            "FB6G", // 2 neurons, glutamate
            "FB6I", // 2 neurons, glutamate
            "FB6Z", // 2 neurons, glutamate
            "FB6A_c", // 2 neurons, glutamate
            "FB6D", // 2 neurons, glutamate
            "FB6M", // 4 neurons, gaba
            "FB6H", // 2 neurons, glutamate
            "FB6T", // 4 neurons, glutamate
            "FB7J", // 4 neurons, glutamate
            "FB7K", // 4 neurons, glutamate
            "FB7B", // 2 neurons, glutamate
        };

        public const int s_LNv_a = 0;
        public const int s_LNv_b = 1;
        public const int LNd_a = 2;
        public const int LNd_b = 3;
        public const int LNd_c = 4;
        public const int DN1pA = 5;
        public const int DN1pB = 6;
        public const int DN1a = 7;
        public const int TuBu01a = 8;
        public const int TuBu01b = 9;
        public const int TuBu02 = 10;
        public const int TuBu03 = 11;
        public const int TuBu04 = 12;
        public const int TuBu05 = 13;
        public const int TuBu06a = 14;
        public const int TuBu06b = 15;
        public const int TuBu07 = 16;
        public const int TuBu08 = 17;
        public const int TuBu09_TuBu10 = 18;
        public const int ER5 = 19;
        public const int ExR1 = 20;
        public const int ExR3 = 21;
        public const int FB6A = 22;
        public const int FB6C = 23;
        public const int FB6E = 24;
        public const int FB6G = 25;
        public const int FB6I = 26;
        public const int FB6Z = 27;
        public const int FB6A_c = 28;
        public const int FB6D = 29;
        public const int FB6M = 30;
        public const int FB6H = 31;
        public const int FB6T = 32;
        public const int FB7J = 33;
        public const int FB7K = 34;
        public const int FB7B = 35;

        public static readonly int[] Clock = { s_LNv_a, s_LNv_b, LNd_a, LNd_b, LNd_c, DN1pA, DN1pB, DN1a };
        public static readonly int[] DfbSleep = { FB6A, FB6C, FB6E, FB6G, FB6I, FB6Z };

        /// <summary>(post, pre, Q8 weight). Sorted by post, then pre.</summary>
        public static readonly short[] Edges = {
            0, 2, 60, // LNd_a -> s-LNv_a: 37 syn, 18.5/neuron
            0, 5, 179, // DN1pA -> s-LNv_a: 327 syn, 163.5/neuron
            0, 6, -41, // DN1pB -> s-LNv_a: 17 syn, 8.5/neuron
            0, 7, -108, // DN1a -> s-LNv_a: 118 syn, 59.0/neuron
            2, 0, 57, // s-LNv_a -> LNd_a: 33 syn, 16.5/neuron
            2, 5, 197, // DN1pA -> LNd_a: 398 syn, 199.0/neuron
            2, 6, -59, // DN1pB -> LNd_a: 35 syn, 17.5/neuron
            2, 7, -139, // DN1a -> LNd_a: 198 syn, 99.0/neuron
            3, 0, 36, // s-LNv_a -> LNd_b: 27 syn, 6.8/neuron
            3, 3, 28, // LNd_b -> LNd_b: 16 syn, 4.0/neuron
            3, 5, 98, // DN1pA -> LNd_b: 196 syn, 49.0/neuron
            3, 6, -37, // DN1pB -> LNd_b: 28 syn, 7.0/neuron
            4, 4, 29, // LNd_c -> LNd_c: 26 syn, 4.3/neuron
            5, 0, 27, // s-LNv_a -> DN1pA: 29 syn, 3.6/neuron
            5, 5, 26, // DN1pA -> DN1pA: 28 syn, 3.5/neuron
            8, 6, -86, // DN1pB -> TuBu01a: 150 syn, 37.5/neuron
            9, 6, -93, // DN1pB -> TuBu01b: 309 syn, 44.1/neuron
            10, 21, 32, // ExR3 -> TuBu02: 58 syn, 5.3/neuron
            12, 12, 23, // TuBu04 -> TuBu04: 25 syn, 2.8/neuron
            14, 6, -20, // DN1pB -> TuBu06a: 4 syn, 2.0/neuron
            14, 9, 26, // TuBu01b -> TuBu06a: 7 syn, 3.5/neuron
            14, 19, -20, // ER5 -> TuBu06a: 4 syn, 2.0/neuron
            15, 19, -23, // ER5 -> TuBu06b: 13 syn, 2.6/neuron
            16, 6, -28, // DN1pB -> TuBu07: 69 syn, 4.1/neuron
            19, 14, 65, // TuBu06a -> ER5: 457 syn, 21.8/neuron
            19, 15, 102, // TuBu06b -> ER5: 1122 syn, 53.4/neuron
            19, 19, -234, // ER5 -> ER5: 5881 syn, 280.0/neuron
            19, 20, -124, // ExR1 -> ER5: 1658 syn, 79.0/neuron
            19, 21, 20, // ExR3 -> ER5: 43 syn, 2.0/neuron
            20, 8, 115, // TuBu01a -> ExR1: 269 syn, 67.2/neuron
            20, 9, 147, // TuBu01b -> ExR1: 442 syn, 110.5/neuron
            20, 10, 163, // TuBu02 -> ExR1: 544 syn, 136.0/neuron
            20, 11, 176, // TuBu03 -> ExR1: 629 syn, 157.2/neuron
            20, 12, 87, // TuBu04 -> ExR1: 154 syn, 38.5/neuron
            20, 13, 34, // TuBu05 -> ExR1: 24 syn, 6.0/neuron
            20, 14, 94, // TuBu06a -> ExR1: 179 syn, 44.8/neuron
            20, 15, 141, // TuBu06b -> ExR1: 408 syn, 102.0/neuron
            20, 16, 212, // TuBu07 -> ExR1: 917 syn, 229.2/neuron
            20, 17, 99, // TuBu08 -> ExR1: 200 syn, 50.0/neuron
            20, 18, 175, // TuBu09,TuBu10 -> ExR1: 626 syn, 156.5/neuron
            20, 19, -448, // ER5 -> ExR1: 4974 syn, 1243.5/neuron
            20, 20, -66, // ExR1 -> ExR1: 88 syn, 22.0/neuron
            20, 21, 80, // ExR3 -> ExR1: 129 syn, 32.2/neuron
            20, 22, 96, // FB6A -> ExR1: 189 syn, 47.2/neuron
            20, 23, 44, // FB6C -> ExR1: 39 syn, 9.8/neuron
            20, 26, -26, // FB6I -> ExR1: 14 syn, 3.5/neuron
            20, 28, -84, // FB6A_c -> ExR1: 145 syn, 36.2/neuron
            20, 29, -54, // FB6D -> ExR1: 60 syn, 15.0/neuron
            20, 30, -23, // FB6M -> ExR1: 11 syn, 2.8/neuron
            20, 33, -40, // FB7J -> ExR1: 32 syn, 8.0/neuron
            20, 34, -34, // FB7K -> ExR1: 24 syn, 6.0/neuron
            20, 35, -28, // FB7B -> ExR1: 16 syn, 4.0/neuron
            21, 6, -33, // DN1pB -> ExR3: 11 syn, 5.5/neuron
            21, 9, 20, // TuBu01b -> ExR3: 4 syn, 2.0/neuron
            21, 10, 46, // TuBu02 -> ExR3: 22 syn, 11.0/neuron
            21, 11, 69, // TuBu03 -> ExR3: 49 syn, 24.5/neuron
            21, 12, 46, // TuBu04 -> ExR3: 22 syn, 11.0/neuron
            21, 17, 22, // TuBu08 -> ExR3: 5 syn, 2.5/neuron
            21, 19, -77, // ER5 -> ExR3: 60 syn, 30.0/neuron
            21, 20, -42, // ExR1 -> ExR3: 18 syn, 9.0/neuron
            21, 21, 55, // ExR3 -> ExR3: 31 syn, 15.5/neuron
            21, 22, 99, // FB6A -> ExR3: 101 syn, 50.5/neuron
            21, 23, 73, // FB6C -> ExR3: 54 syn, 27.0/neuron
            21, 24, 24, // FB6E -> ExR3: 6 syn, 3.0/neuron
            21, 26, -26, // FB6I -> ExR3: 7 syn, 3.5/neuron
            21, 27, -22, // FB6Z -> ExR3: 5 syn, 2.5/neuron
            21, 28, -115, // FB6A_c -> ExR3: 134 syn, 67.0/neuron
            21, 29, -83, // FB6D -> ExR3: 70 syn, 35.0/neuron
            21, 30, -259, // FB6M -> ExR3: 684 syn, 342.0/neuron
            21, 31, -20, // FB6H -> ExR3: 4 syn, 2.0/neuron
            22, 21, -56, // ExR3 -> FB6A: 63 syn, 15.8/neuron
            22, 22, 93, // FB6A -> FB6A: 178 syn, 44.5/neuron
            22, 23, 99, // FB6C -> FB6A: 200 syn, 50.0/neuron
            22, 24, 41, // FB6E -> FB6A: 35 syn, 8.8/neuron
            22, 25, -29, // FB6G -> FB6A: 17 syn, 4.2/neuron
            22, 26, -42, // FB6I -> FB6A: 36 syn, 9.0/neuron
            22, 28, -47, // FB6A_c -> FB6A: 45 syn, 11.2/neuron
            22, 29, -68, // FB6D -> FB6A: 95 syn, 23.8/neuron
            22, 30, -60, // FB6M -> FB6A: 74 syn, 18.5/neuron
            22, 31, -60, // FB6H -> FB6A: 74 syn, 18.5/neuron
            22, 32, -31, // FB6T -> FB6A: 20 syn, 5.0/neuron
            22, 35, -21, // FB7B -> FB6A: 9 syn, 2.2/neuron
            23, 22, 57, // FB6A -> FB6C: 148 syn, 16.4/neuron
            23, 23, 88, // FB6C -> FB6C: 355 syn, 39.4/neuron
            23, 24, 20, // FB6E -> FB6C: 18 syn, 2.0/neuron
            23, 26, -27, // FB6I -> FB6C: 34 syn, 3.8/neuron
            23, 27, -33, // FB6Z -> FB6C: 49 syn, 5.4/neuron
            23, 28, -31, // FB6A_c -> FB6C: 43 syn, 4.8/neuron
            23, 29, -32, // FB6D -> FB6C: 48 syn, 5.3/neuron
            23, 31, -58, // FB6H -> FB6C: 154 syn, 17.1/neuron
            24, 21, -38, // ExR3 -> FB6E: 15 syn, 7.5/neuron
            24, 22, 52, // FB6A -> FB6E: 28 syn, 14.0/neuron
            24, 23, 73, // FB6C -> FB6E: 55 syn, 27.5/neuron
            24, 24, 114, // FB6E -> FB6E: 132 syn, 66.0/neuron
            24, 25, -51, // FB6G -> FB6E: 27 syn, 13.5/neuron
            24, 26, -28, // FB6I -> FB6E: 8 syn, 4.0/neuron
            24, 27, -34, // FB6Z -> FB6E: 12 syn, 6.0/neuron
            24, 28, -37, // FB6A_c -> FB6E: 14 syn, 7.0/neuron
            24, 29, -42, // FB6D -> FB6E: 18 syn, 9.0/neuron
            24, 31, -63, // FB6H -> FB6E: 40 syn, 20.0/neuron
            24, 32, -191, // FB6T -> FB6E: 373 syn, 186.5/neuron
            24, 35, -20, // FB7B -> FB6E: 4 syn, 2.0/neuron
            25, 22, 52, // FB6A -> FB6G: 28 syn, 14.0/neuron
            25, 24, 70, // FB6E -> FB6G: 50 syn, 25.0/neuron
            25, 25, -38, // FB6G -> FB6G: 15 syn, 7.5/neuron
            25, 26, -45, // FB6I -> FB6G: 21 syn, 10.5/neuron
            25, 27, -26, // FB6Z -> FB6G: 7 syn, 3.5/neuron
            25, 31, -133, // FB6H -> FB6G: 181 syn, 90.5/neuron
            25, 32, -154, // FB6T -> FB6G: 241 syn, 120.5/neuron
            25, 35, -42, // FB7B -> FB6G: 18 syn, 9.0/neuron
            26, 21, -28, // ExR3 -> FB6I: 8 syn, 4.0/neuron
            26, 22, 65, // FB6A -> FB6I: 43 syn, 21.5/neuron
            26, 23, 79, // FB6C -> FB6I: 64 syn, 32.0/neuron
            26, 24, 56, // FB6E -> FB6I: 32 syn, 16.0/neuron
            26, 25, -34, // FB6G -> FB6I: 12 syn, 6.0/neuron
            26, 26, -26, // FB6I -> FB6I: 7 syn, 3.5/neuron
            26, 27, -41, // FB6Z -> FB6I: 17 syn, 8.5/neuron
            26, 28, -26, // FB6A_c -> FB6I: 7 syn, 3.5/neuron
            26, 29, -36, // FB6D -> FB6I: 13 syn, 6.5/neuron
            26, 31, -126, // FB6H -> FB6I: 162 syn, 81.0/neuron
            26, 35, -20, // FB7B -> FB6I: 4 syn, 2.0/neuron
            27, 24, 100, // FB6E -> FB6Z: 103 syn, 51.5/neuron
            27, 26, -24, // FB6I -> FB6Z: 6 syn, 3.0/neuron
            27, 27, -38, // FB6Z -> FB6Z: 15 syn, 7.5/neuron
            27, 31, -86, // FB6H -> FB6Z: 76 syn, 38.0/neuron
            27, 32, -89, // FB6T -> FB6Z: 81 syn, 40.5/neuron
            27, 34, 24, // FB7K -> FB6Z: 6 syn, 3.0/neuron
            27, 35, -36, // FB7B -> FB6Z: 13 syn, 6.5/neuron
            28, 21, -86, // ExR3 -> FB6A_c: 75 syn, 37.5/neuron
            28, 22, 80, // FB6A -> FB6A_c: 65 syn, 32.5/neuron
            28, 23, 80, // FB6C -> FB6A_c: 66 syn, 33.0/neuron
            28, 24, 31, // FB6E -> FB6A_c: 10 syn, 5.0/neuron
            28, 26, -20, // FB6I -> FB6A_c: 4 syn, 2.0/neuron
            28, 27, -20, // FB6Z -> FB6A_c: 4 syn, 2.0/neuron
            28, 28, -63, // FB6A_c -> FB6A_c: 41 syn, 20.5/neuron
            28, 29, -64, // FB6D -> FB6A_c: 42 syn, 21.0/neuron
            28, 30, -63, // FB6M -> FB6A_c: 41 syn, 20.5/neuron
            28, 31, -30, // FB6H -> FB6A_c: 9 syn, 4.5/neuron
            29, 21, -66, // ExR3 -> FB6D: 44 syn, 22.0/neuron
            29, 22, 115, // FB6A -> FB6D: 134 syn, 67.0/neuron
            29, 23, 90, // FB6C -> FB6D: 82 syn, 41.0/neuron
            29, 24, 28, // FB6E -> FB6D: 8 syn, 4.0/neuron
            29, 26, -37, // FB6I -> FB6D: 14 syn, 7.0/neuron
            29, 28, -71, // FB6A_c -> FB6D: 52 syn, 26.0/neuron
            29, 29, -45, // FB6D -> FB6D: 21 syn, 10.5/neuron
            29, 30, -20, // FB6M -> FB6D: 4 syn, 2.0/neuron
            29, 31, -42, // FB6H -> FB6D: 18 syn, 9.0/neuron
            30, 21, -91, // ExR3 -> FB6M: 170 syn, 42.5/neuron
            30, 22, 81, // FB6A -> FB6M: 134 syn, 33.5/neuron
            30, 23, 69, // FB6C -> FB6M: 97 syn, 24.2/neuron
            30, 24, 23, // FB6E -> FB6M: 11 syn, 2.8/neuron
            30, 25, -31, // FB6G -> FB6M: 19 syn, 4.8/neuron
            30, 26, -26, // FB6I -> FB6M: 14 syn, 3.5/neuron
            30, 27, -26, // FB6Z -> FB6M: 14 syn, 3.5/neuron
            30, 28, -58, // FB6A_c -> FB6M: 68 syn, 17.0/neuron
            30, 29, -42, // FB6D -> FB6M: 36 syn, 9.0/neuron
            30, 31, -20, // FB6H -> FB6M: 8 syn, 2.0/neuron
            30, 34, -23, // FB7K -> FB6M: 11 syn, 2.8/neuron
            30, 35, -21, // FB7B -> FB6M: 9 syn, 2.2/neuron
            31, 21, -20, // ExR3 -> FB6H: 4 syn, 2.0/neuron
            31, 22, 113, // FB6A -> FB6H: 130 syn, 65.0/neuron
            31, 24, 62, // FB6E -> FB6H: 39 syn, 19.5/neuron
            31, 25, -61, // FB6G -> FB6H: 38 syn, 19.0/neuron
            31, 26, -77, // FB6I -> FB6H: 60 syn, 30.0/neuron
            31, 27, -41, // FB6Z -> FB6H: 17 syn, 8.5/neuron
            31, 28, -40, // FB6A_c -> FB6H: 16 syn, 8.0/neuron
            31, 29, -33, // FB6D -> FB6H: 11 syn, 5.5/neuron
            31, 30, -20, // FB6M -> FB6H: 4 syn, 2.0/neuron
            31, 31, -78, // FB6H -> FB6H: 62 syn, 31.0/neuron
            31, 32, -63, // FB6T -> FB6H: 40 syn, 20.0/neuron
            31, 33, -46, // FB7J -> FB6H: 22 syn, 11.0/neuron
            32, 23, -21, // FB6C -> FB6T: 9 syn, 2.2/neuron
            32, 24, 25, // FB6E -> FB6T: 13 syn, 3.2/neuron
            32, 25, -43, // FB6G -> FB6T: 38 syn, 9.5/neuron
            32, 31, -21, // FB6H -> FB6T: 9 syn, 2.2/neuron
            33, 20, -32, // ExR1 -> FB7J: 21 syn, 5.2/neuron
            33, 23, -24, // FB6C -> FB7J: 12 syn, 3.0/neuron
            33, 31, -44, // FB6H -> FB7J: 39 syn, 9.8/neuron
            33, 34, -30, // FB7K -> FB7J: 18 syn, 4.5/neuron
            33, 35, -39, // FB7B -> FB7J: 31 syn, 7.8/neuron
            34, 32, -50, // FB6T -> FB7K: 52 syn, 13.0/neuron
            34, 33, -20, // FB7J -> FB7K: 8 syn, 2.0/neuron
            34, 34, -66, // FB7K -> FB7K: 90 syn, 22.5/neuron
            34, 35, -102, // FB7B -> FB7K: 214 syn, 53.5/neuron
            35, 6, -26, // DN1pB -> FB7B: 7 syn, 3.5/neuron
            35, 20, -31, // ExR1 -> FB7B: 10 syn, 5.0/neuron
            35, 22, 31, // FB6A -> FB7B: 10 syn, 5.0/neuron
            35, 23, -34, // FB6C -> FB7B: 12 syn, 6.0/neuron
            35, 31, -20, // FB6H -> FB7B: 4 syn, 2.0/neuron
            35, 32, -40, // FB6T -> FB7B: 16 syn, 8.0/neuron
            35, 33, -34, // FB7J -> FB7B: 12 syn, 6.0/neuron
            35, 34, -49, // FB7K -> FB7B: 25 syn, 12.5/neuron
        };
    }
}
