"""
Extract the Drosophila sleep/clock circuit from the FlyWire connectome (v783) and emit
Source/Brain/FlyConnectomeSleep.g.cs for the Fly brain.

Data (not shipped with the mod):
  - FlyWire neuron annotations (cell types, neurotransmitters):
      https://github.com/flyconnectome/flywire_annotations  Supplemental_file1_neuron_annotations.tsv
  - FlyWire v783 connectivity with neurotransmitter sign, as packaged by Shiu et al. (2024):
      https://github.com/philshiu/Drosophila_brain_model  Connectivity_783.parquet
    (derived from https://zenodo.org/records/10676866, CC-BY 4.0)

Method:
  1. Select cell types of the circadian -> sleep-homeostat pathway:
     clock neurons (s-LNv, LNd, DN1p, DN1a) -> TuBu (anterior bulb) -> ER5 ring neurons /
     ExR1 helicon cells / ExR3 -> dorsal fan-shaped body (FB6/FB7 tangentials).
  2. Collapse every neuron of a cell type (both hemispheres) into one node.
  3. Edge strength = total synapses / number of post-synaptic neurons of that type;
     sign = synapse-weighted neurotransmitter sign (ACh +, GABA/Glu -), as in Shiu et al.
  4. Dopamine: the Shiu table treats all non-GABA/glutamate transmitters as excitatory. Dopamine onto
     dFB neurons is inhibitory (Dop1R2; Pimentel et al. 2016, wake-promoting), so dopaminergic edges onto
     FB6/FB7 types are flipped negative.
  5. Keep edges with >= MIN_PER_POST synapses per post neuron; compress to Q8 weights with a
     square-root curve (large counts would otherwise saturate the fixed-point model).

Usage: python build_connectome.py <annotations.tsv> <Connectivity_783.parquet> <out .g.cs>
"""
import sys, math
import pandas as pd

CLOCK = ['s-LNv_a', 's-LNv_b', 'LNd_a', 'LNd_b', 'LNd_c', 'DN1pA', 'DN1pB', 'DN1a']
TUBU = ['TuBu01a', 'TuBu01b', 'TuBu02', 'TuBu03', 'TuBu04', 'TuBu05', 'TuBu06a', 'TuBu06b',
        'TuBu07', 'TuBu08', 'TuBu09,TuBu10']
RING = ['ER5', 'ExR1', 'ExR3']
# Dorsal fan-shaped body: the 23E10 "dFB" sleep-promoting types plus FB6/7 types that
# exchange strong connections with the ring/helicon hub.
DFB_SLEEP = ['FB6A', 'FB6C', 'FB6E', 'FB6G', 'FB6I', 'FB6Z']
DFB_OTHER = ['FB6A_c', 'FB6D', 'FB6M', 'FB6H', 'FB6T', 'FB7J', 'FB7K', 'FB7B']
TYPES = CLOCK + TUBU + RING + DFB_SLEEP + DFB_OTHER

MIN_PER_POST = 2.0
SQRT_GAIN = 14.0     # Q8 weight = sign * min(WMAX, SQRT_GAIN * sqrt(per_post))
WMAX = 448


def main(annot_path, conn_path, out_path):
    a = pd.read_csv(annot_path, sep='\t', low_memory=False, usecols=['root_id', 'cell_type', 'top_nt'])
    sel = a[a.cell_type.isin(TYPES)]
    missing = sorted(set(TYPES) - set(sel.cell_type))
    if missing:
        raise SystemExit(f'cell types not found: {missing}')
    type_of = dict(zip(sel.root_id, sel.cell_type))
    n_by = sel.groupby('cell_type').size()
    nt_by = sel.groupby('cell_type').top_nt.agg(lambda s: s.mode().iloc[0])

    c = pd.read_parquet(conn_path, columns=['Presynaptic_ID', 'Postsynaptic_ID', 'Connectivity', 'Excitatory x Connectivity'])
    e = c[c.Presynaptic_ID.isin(type_of) & c.Postsynaptic_ID.isin(type_of)].copy()
    e['pre'] = e.Presynaptic_ID.map(type_of)
    e['post'] = e.Postsynaptic_ID.map(type_of)
    g = e.groupby(['pre', 'post']).agg(syn=('Connectivity', 'sum'), signed=('Excitatory x Connectivity', 'sum')).reset_index()
    g['per_post'] = g.syn / g.post.map(n_by)
    g['sign'] = g.signed / g.syn            # -1..1, synapse-weighted
    da = set(nt_by[nt_by == 'dopamine'].index)
    flip = g.pre.isin(da) & g.post.str.startswith('FB')
    g.loc[flip, 'sign'] = -g.loc[flip, 'sign'].abs()
    g = g[(g.per_post >= MIN_PER_POST) & (g.sign.abs() >= 0.2)]

    idx = {t: i for i, t in enumerate(TYPES)}
    edges = []
    for r in g.itertuples():
        w = int(round(min(WMAX, SQRT_GAIN * math.sqrt(r.per_post)) * (1 if r.sign > 0 else -1)))
        if w != 0:
            edges.append((idx[r.post], idx[r.pre], w, int(r.syn), r.per_post))
    edges.sort()

    def cs_name(t):
        return t.replace('-', '_').replace(',', '_')

    lines = []
    lines.append('// <auto-generated> by Tools/build_connectome.py. Do not edit by hand. </auto-generated>')
    lines.append('// Drosophila circadian -> sleep-homeostat circuit, FlyWire whole-brain connectome v783.')
    lines.append('// Data: FlyWire Consortium (Dorkenwald et al. 2024; Schlegel et al. 2024), CC-BY 4.0,')
    lines.append('//       connectivity/sign table from Shiu et al. 2024 (github.com/philshiu/Drosophila_brain_model).')
    lines.append(f'// {len(TYPES)} cell-type nodes ({int(n_by.sum())} neurons), {len(edges)} edges '
                 f'({int(sum(x[3] for x in edges))} synapses).')
    lines.append('namespace FlyXenotype.Brain')
    lines.append('{')
    lines.append('    public static class FlyConnectomeSleep')
    lines.append('    {')
    lines.append('        public static readonly string[] Types = {')
    for t in TYPES:
        lines.append(f'            "{t}", // {n_by[t]} neurons, {nt_by[t]}')
    lines.append('        };')
    lines.append('')
    for t in TYPES:
        lines.append(f'        public const int {cs_name(t)} = {idx[t]};')
    lines.append('')
    lines.append(f'        public static readonly int[] Clock = {{ {", ".join(cs_name(t) for t in CLOCK)} }};')
    lines.append(f'        public static readonly int[] DfbSleep = {{ {", ".join(cs_name(t) for t in DFB_SLEEP)} }};')
    lines.append('')
    lines.append('        /// <summary>(post, pre, Q8 weight). Sorted by post, then pre.</summary>')
    lines.append('        public static readonly short[] Edges = {')
    for post, pre, w, syn, pp in edges:
        lines.append(f'            {post}, {pre}, {w}, // {TYPES[pre]} -> {TYPES[post]}: {syn} syn, {pp:.1f}/neuron')
    lines.append('        };')
    lines.append('    }')
    lines.append('}')
    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{len(TYPES)} nodes, {len(edges)} edges -> {out_path}')


if __name__ == '__main__':
    main(*sys.argv[1:4])
